### PR TITLE
Remove the Gradle Secrets plugin

### PR DESCRIPTION
**Pull request by ianthetechie**
I forgot to put this in the last PR... Halfway through integrating autocomplete search, I found a better way of doing this on Android which didn't require depending on yet another Gradle plugin.

### CODE REVIEW

**Review by Archdoog — COMMENTED** [review]
Looks good. Only note is, could we make this optional in this PR and default back to the demo tiles if not set?

I figure this is a good short PR to do that as well. (Happy to merge as is though first)

**Comment by ianthetechie** [comment]
Ahh, good coll. Though at the moment, the search box can't work and we don't have simulated routes back yet.

**Comment by ianthetechie** [comment]
App now works without an API key and doesn't crash ;)

image

**Comment by Archdoog** [comment]
Ah fair. In that case we can just create a ticket

**Comment by ianthetechie** [comment]
Yeah, we know we need to to simulated routes anyways (without recompiling) in the wake of this anyways.

**Pull request merged**
